baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Colwich Elementary Spring Carnival 2022'
description = 'Come join us on April 29th from 5:00pm to 7:30pm. There are plenty of games for the kids to enjoy, raffles to be won, and money to be raised for Colwich Elementary School.'
theme = "ColwichTheme"
