backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "themes/ColwichTheme/static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://colwichhso.com
display_url: https://colwichhso.com
logo_url: https://colwichhso.com/images/logo/hsonew.png

editor:
  preview: false

collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Top Level Pages" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Full URL", name: "fullUrl", widget: "string"}
      - {label: "Open Graph Image", name: "pageImage", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "sponsors" # Used in routes, e.g., /admin/collections/blog
    label: "Sponsors" # Used in the UI
    folder: "content/sponsors" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Content Type", name: "type", widget: "hidden", default: "sponsor"}
      - {label: "Logo", name: "logo", widget: "image", media_folder: "/themes/ColwichTheme/static/images/sponsors", hint: "Please only upload SVG's for sponsor images."}
      - {label: "Active", name: "active", widget: "boolean", hint: "Only Active sponsors show up in the widget. Designed for 6 active sponsors at a time."}
  - name: "forms" # Used in routes, e.g., /admin/collections/blog
    label: "Forms" # Used in the UI
    folder: "content/forms" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string", hint:"This shows up on search engines, and in social media links."}
      - {label: "Content Type", name: "type", widget: "hidden", default: "forms"}
      - {label: "Local URL", name: "url", widget: "hidden"}
      - {label: "Full URL", name: "fullUrl", widget: "hidden"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Shout Out", name: "shoutout", widget: "string"}
      - {label: "Overview", name: "overview", widget: "markdown"}
      - {label: "FAQ Category", name: "faq_category", widget: "string"}
      - {label: "Wufoo Form", name: "formEmbed", widget: "string"}
      - {label: "Page Modules", name: "modules", widget: "list", field: {label: "Module", widget: "string", name: "module"}}